"""Task #3131 — gated merge regenerates conflicts in declared generated files.

Every parallel ``--tasks`` batch failed to merge its second and later branches
with "merge and rebase conflict: CONFLICT (content): Merge conflict in
equipa/MODULE_DEPENDENCY_REPORT.md", a file fully generated by
``scripts/gen_module_report.py``. These tests run the real gate and merge on
real temporary git repositories:

* a conflict ONLY in the report is resolved by regenerating it from the merged
  tree; the recorded merged SHA is the resolution commit, and the resolution
  differs from ``git merge-tree``'s merge in the report alone;
* a mixed conflict, a branch that changed the generator, a generator that
  fails or times out, and a project without the generator all end
  ``merge_failed`` with the main checkout clean and the branch preserved;
* the generator runs with the scrubbed agent environment, isolated Python,
  and outside the main checkout;
* the guard's merge-integrity check (task #3116) accepts only a resolution
  that touches the regenerated files and nothing else.

Every test runs with a throwaway HOME, so the operator's real global git
config is never read or written.

Copyright 2026 Forgeborn
"""

from __future__ import annotations

import asyncio
import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

import pytest

from equipa.dispatch import _gated_merge_task
from equipa.git_ops import reset_global_git_config_pin
from equipa.loops import ARTIFACTS_DIR_NAME
from equipa.merge_integrity import DefaultBranchGuard

TASK = 3131
BRANCH = f"forge-task-{TASK}"
REPORT = "equipa/MODULE_DEPENDENCY_REPORT.md"
GENERATOR = "scripts/gen_module_report.py"
REAL_GENERATOR = Path(__file__).resolve().parents[1] / GENERATOR


# --- git helpers -------------------------------------------------------------


def _git(cwd: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", *args], cwd=str(cwd), text=True, capture_output=True,
    )
    if result.returncode != 0:
        raise AssertionError(f"git {' '.join(args)} failed: {result.stderr}")
    return result.stdout.strip()


def _sha(repo: Path, ref: str) -> str:
    return _git(repo, "rev-parse", "--verify", f"{ref}^{{commit}}")


def _write(root: Path, rel: str, text: str) -> None:
    path = root / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _commit_all(cwd: Path, message: str) -> str:
    _git(cwd, "add", "-A")
    _git(cwd, "commit", "-q", "-m", message)
    return _sha(cwd, "HEAD")


def _run_real_generator(root: Path) -> None:
    subprocess.run(
        [sys.executable, str(root / GENERATOR)], cwd=str(root), check=True,
        capture_output=True,
    )


def _merge_head_exists(repo: Path) -> bool:
    return subprocess.run(
        ["git", "rev-parse", "--verify", "--quiet", "MERGE_HEAD"],
        cwd=str(repo), capture_output=True,
    ).returncode == 0


def _merge_tree(repo: Path, ours: str, theirs: str) -> tuple[int, str, list[str]]:
    result = subprocess.run(
        ["git", "merge-tree", "--write-tree", "--no-messages", "--name-only",
         ours, theirs],
        cwd=str(repo), text=True, capture_output=True,
    )
    lines = result.stdout.splitlines()
    return result.returncode, lines[0], [line for line in lines[1:] if line]


def _write_clean_review(repo: Path) -> None:
    """A clean artifact; the suite's conftest permits the unrecorded run."""
    _write(
        repo, f"{ARTIFACTS_DIR_NAME}/SECURITY-REVIEW-{TASK}.md",
        "# Security Review\n\nNo findings.\n\n## Counts\n"
        "CRITICAL: 0 | HIGH: 0 | MEDIUM: 0 | LOW: 0 | INFO: 0\n",
    )


def _gate(repo: Path, worktree: Path) -> tuple[str, DefaultBranchGuard]:
    _write_clean_review(repo)
    guard = asyncio.run(DefaultBranchGuard.snapshot(repo))
    status = asyncio.run(_gated_merge_task(
        repo=repo, branch=BRANCH, outcome="tests_passed", task_id=TASK,
        guard=guard, worktree_dir=str(worktree),
    ))
    return status, guard


# --- fixtures ----------------------------------------------------------------


@pytest.fixture(autouse=True)
def isolated_home(tmp_path: Path, monkeypatch) -> Path:
    home = tmp_path / "home"
    home.mkdir()
    monkeypatch.setenv("HOME", str(home))
    monkeypatch.setenv("XDG_CONFIG_HOME", str(home / ".config"))
    for name in (
        "GIT_CONFIG_GLOBAL", "GIT_CONFIG_SYSTEM", "GIT_CONFIG_NOSYSTEM",
        "GIT_ATTR_NOSYSTEM", "GIT_DIR", "GIT_WORK_TREE", "GIT_INDEX_FILE",
    ):
        monkeypatch.delenv(name, raising=False)
    reset_global_git_config_pin()
    yield home
    reset_global_git_config_pin()


def _init_repo(path: Path) -> Path:
    path.mkdir()
    _git(path, "init", "-q", "-b", "main")
    _git(path, "config", "user.email", "test@forgeborn.local")
    _git(path, "config", "user.name", "Test")
    _git(path, "config", "commit.gpgsign", "false")
    _write(path, ".gitignore", f"{ARTIFACTS_DIR_NAME}/\n.forge-worktrees/\n")
    _write(path, "equipa/__init__.py", "")
    _write(path, "equipa/core.py", "VALUE = 'base'\n")
    return path


@pytest.fixture
def repo(tmp_path: Path) -> Path:
    """A project carrying the real generator and its committed report."""
    path = _init_repo(tmp_path / "repo")
    (path / "scripts").mkdir()
    shutil.copyfile(REAL_GENERATOR, path / GENERATOR)
    _run_real_generator(path)
    _commit_all(path, "base")
    return path


def _add_task_worktree(repo: Path) -> Path:
    worktree = repo / ".forge-worktrees" / f"task-{TASK}"
    _git(repo, "worktree", "add", "-q", "-b", BRANCH, str(worktree), "main")
    return worktree


def _diverge_with_report_conflict(repo: Path) -> tuple[Path, str, str]:
    """Two feature modules, each side regenerating the report: the classic
    parallel-batch shape. Returns (worktree, branch SHA, main SHA)."""
    worktree = _add_task_worktree(repo)
    _write(worktree, "equipa/feature_b.py", "from equipa import core\n")
    _run_real_generator(worktree)
    branch_sha = _commit_all(worktree, "feature b")
    _write(repo, "equipa/feature_c.py", "from equipa import core\n")
    _run_real_generator(repo)
    main_sha = _commit_all(repo, "feature c")
    rc, _tree, conflicted = _merge_tree(repo, main_sha, branch_sha)
    assert (rc, conflicted) == (1, [REPORT]), "precondition: report-only conflict"
    return worktree, branch_sha, main_sha


def _assert_failed_cleanly(
    repo: Path, guard: DefaultBranchGuard, main_sha: str, branch_sha: str,
) -> None:
    assert _sha(repo, "main") == main_sha
    assert _sha(repo, BRANCH) == branch_sha
    assert _git(repo, "status", "--porcelain") == ""
    assert not _merge_head_exists(repo)
    assert not guard.tripped
    assert guard.outcomes[TASK].merged_sha is None


# --- the declarative list ----------------------------------------------------


def test_report_is_declared_with_its_generator():
    from equipa.generated_files import GENERATED_FILES, generated_file

    spec = generated_file(REPORT)
    assert spec is not None and spec in GENERATED_FILES
    assert spec.generator == GENERATOR
    assert "--stdout" in spec.args
    assert generated_file("equipa/core.py") is None
    assert REAL_GENERATOR.is_file()


# --- generated-only conflict: merged ------------------------------------------


def test_report_only_conflict_is_regenerated_and_merged(repo, capsys):
    worktree, branch_sha, main_sha = _diverge_with_report_conflict(repo)

    status, guard = _gate(repo, worktree)

    assert status == "merged", guard.outcomes[TASK]
    tip = _sha(repo, "main")
    outcome = guard.outcomes[TASK]
    assert outcome.merged_sha == tip, "the recorded merged SHA is the final commit"
    assert REPORT in outcome.reason
    assert _git(repo, "rev-list", "--parents", "-n", "1", tip).split()[1:] == [
        main_sha, branch_sha,
    ]
    assert guard.expected_sha == tip and not guard.tripped
    # The committed report is exactly a fresh generation of the merged tree.
    check = subprocess.run(
        [sys.executable, GENERATOR, "--check"], cwd=str(repo),
        capture_output=True, text=True,
    )
    assert check.returncode == 0, check.stderr
    report = (repo / REPORT).read_text(encoding="utf-8")
    assert "feature_b" in report and "feature_c" in report
    assert "<<<<<<<" not in report
    # The resolution commit differs from git's own merge in the report ONLY.
    _rc, conflicted_tree, _ = _merge_tree(repo, main_sha, branch_sha)
    assert _git(repo, "diff-tree", "-r", "--name-only", conflicted_tree,
                f"{tip}^{{tree}}").splitlines() == [REPORT]
    assert _git(repo, "status", "--porcelain") == ""
    assert not _merge_head_exists(repo)
    err = capsys.readouterr().err
    assert "event=generated-files-regenerated" in err
    assert f"files={REPORT}" in err
    assert f"merged_sha={tip}" in err


# --- mixed conflict: today's behaviour ----------------------------------------


def test_mixed_conflict_keeps_todays_merge_failed(repo, capsys):
    worktree = _add_task_worktree(repo)
    _write(worktree, "equipa/core.py", "VALUE = 'branch'\n")
    _write(worktree, "equipa/feature_b.py", "from equipa import core\n")
    _run_real_generator(worktree)
    branch_sha = _commit_all(worktree, "branch edits core")
    _write(repo, "equipa/core.py", "VALUE = 'main'\n")
    _write(repo, "equipa/feature_c.py", "from equipa import core\n")
    _run_real_generator(repo)
    main_sha = _commit_all(repo, "main edits core")
    main_report = (repo / REPORT).read_bytes()
    assert set(_merge_tree(repo, main_sha, branch_sha)[2]) == {
        "equipa/core.py", REPORT,
    }

    status, guard = _gate(repo, worktree)

    assert status == "merge_failed"
    assert guard.outcomes[TASK].reason.startswith("merge and rebase conflict:")
    _assert_failed_cleanly(repo, guard, main_sha, branch_sha)
    assert (repo / REPORT).read_bytes() == main_report
    assert "generated-files" not in capsys.readouterr().err


# --- branch changed the generator: never run ----------------------------------


def test_branch_that_changed_the_generator_is_not_run(repo, tmp_path, capsys):
    marker = tmp_path / "generator-ran"
    worktree = _add_task_worktree(repo)
    _write(worktree, "equipa/feature_b.py", "from equipa import core\n")
    _run_real_generator(worktree)
    hostile = (
        f"import pathlib\npathlib.Path({str(marker)!r}).write_text('ran')\n"
        + (worktree / GENERATOR).read_text(encoding="utf-8")
    )
    _write(worktree, GENERATOR, hostile)
    branch_sha = _commit_all(worktree, "feature b and a new generator")
    _write(repo, "equipa/feature_c.py", "from equipa import core\n")
    _run_real_generator(repo)
    main_sha = _commit_all(repo, "feature c")
    assert _merge_tree(repo, main_sha, branch_sha)[2] == [REPORT]

    status, guard = _gate(repo, worktree)

    assert status == "merge_failed"
    reason = guard.outcomes[TASK].reason
    assert f"the task branch changed the generator {GENERATOR}" in reason
    assert REPORT in reason
    assert not marker.exists(), "the branch's generator must never run"
    _assert_failed_cleanly(repo, guard, main_sha, branch_sha)
    assert "event=generated-files-not-regenerated" in capsys.readouterr().err


def test_generator_changed_on_the_default_branch_is_not_blamed_on_the_task(
    tmp_path,
):
    """Blob equality with the pinned default branch is still required, but
    when only the default branch moved the generator the reason says so:
    an operator must not read it as the agent tampering with the generator."""
    marker = tmp_path / "generator-ran"
    writes_marker = (
        f"import pathlib\npathlib.Path({str(marker)!r}).write_text('ran')\n"
        "print('fresh report')\n"
    )
    repo = _repo_with_generator(tmp_path, writes_marker)
    worktree = _add_task_worktree(repo)
    _write(worktree, "equipa/feature_b.py", "B = 1\n")
    _write(worktree, REPORT, "report from the branch\n")
    branch_sha = _commit_all(worktree, "branch leaves the generator alone")
    _write(repo, GENERATOR, "# updated on main\n" + writes_marker)
    _write(repo, REPORT, "report from main\n")
    main_sha = _commit_all(repo, "main updates the generator")

    status, guard = _gate(repo, worktree)

    assert status == "merge_failed"
    reason = guard.outcomes[TASK].reason
    assert f"the default branch changed the generator {GENERATOR}" in reason
    assert "task branch changed" not in reason
    assert not marker.exists(), "neither side's generator may run"
    _assert_failed_cleanly(repo, guard, main_sha, branch_sha)


# --- branch-written code in the merged tree is data, never run ----------------


def test_branch_modules_in_the_merged_tree_are_never_imported(repo, tmp_path):
    """The unchanged generator only parses the tree: a branch that plants
    stdlib shadows next to it, site hooks at the root, or a feature module
    with import-time code gets its report regenerated without any of it
    running."""
    markers = tmp_path / "markers"
    markers.mkdir()
    worktree = _add_task_worktree(repo)

    def plant(rel: str, name: str) -> None:
        _write(worktree, rel, (
            "import pathlib\n"
            f"pathlib.Path({str(markers / name)!r}).write_text('ran')\n"
            "from equipa import core\n"
        ))

    plant("equipa/feature_b.py", "feature-b")
    # The branch's report is generated before the shadows exist: the
    # fixture runs the generator without -I, so they would break it here.
    _run_real_generator(worktree)
    for rel, name in (
        ("scripts/ast.py", "shadow-ast"),
        ("scripts/argparse.py", "shadow-argparse"),
        ("scripts/usercustomize.py", "usercustomize"),
        ("sitecustomize.py", "sitecustomize"),
    ):
        plant(rel, name)
    branch_sha = _commit_all(worktree, "feature b with planted modules")
    _write(repo, "equipa/feature_c.py", "from equipa import core\n")
    _run_real_generator(repo)
    main_sha = _commit_all(repo, "feature c")
    assert _merge_tree(repo, main_sha, branch_sha)[2] == [REPORT]

    status, guard = _gate(repo, worktree)

    assert status == "merged", guard.outcomes[TASK]
    assert sorted(path.name for path in markers.iterdir()) == []
    report = (repo / REPORT).read_text(encoding="utf-8")
    assert "feature_b" in report and "feature_c" in report


# --- generator fails or times out ---------------------------------------------


def _repo_with_generator(tmp_path: Path, generator_source: str) -> Path:
    """A project whose (trusted, unchanged) generator is ``generator_source``."""
    path = _init_repo(tmp_path / "repo")
    _write(path, GENERATOR, generator_source)
    _write(path, REPORT, "report v0\n")
    _commit_all(path, "base")
    return path


def _diverge_by_hand(repo: Path) -> tuple[Path, str, str]:
    worktree = _add_task_worktree(repo)
    _write(worktree, "equipa/feature_b.py", "B = 1\n")
    _write(worktree, REPORT, "report from the branch\n")
    branch_sha = _commit_all(worktree, "branch")
    _write(repo, "equipa/feature_c.py", "C = 1\n")
    _write(repo, REPORT, "report from main\n")
    main_sha = _commit_all(repo, "main")
    return worktree, branch_sha, main_sha


def _alive(pid: int) -> bool:
    try:
        state = Path(f"/proc/{pid}/stat").read_text().rsplit(")", 1)[1].split()[0]
    except (FileNotFoundError, IndexError):
        return False
    return state != "Z"


def test_generator_timeout_kills_its_group_and_fails_cleanly(
    tmp_path, monkeypatch, capsys,
):
    pid_file = tmp_path / "grandchild.pid"
    repo = _repo_with_generator(tmp_path, (
        "import pathlib, subprocess, time\n"
        "child = subprocess.Popen(['sleep', '120'])\n"
        f"pathlib.Path({str(pid_file)!r}).write_text(str(child.pid))\n"
        "time.sleep(120)\n"
    ))
    worktree, branch_sha, main_sha = _diverge_by_hand(repo)
    monkeypatch.setattr("equipa.generated_files.GENERATOR_TIMEOUT_SECONDS", 2)

    started = time.monotonic()
    status, guard = _gate(repo, worktree)

    assert time.monotonic() - started < 60
    assert status == "merge_failed"
    assert "timed out after 2s" in guard.outcomes[TASK].reason
    _assert_failed_cleanly(repo, guard, main_sha, branch_sha)
    assert (repo / REPORT).read_text(encoding="utf-8") == "report from main\n"
    grandchild = int(pid_file.read_text())
    deadline = time.monotonic() + 5
    while _alive(grandchild) and time.monotonic() < deadline:
        time.sleep(0.05)
    assert not _alive(grandchild), "the generator's process group was not killed"


@pytest.mark.parametrize(
    ("source", "expected"),
    [
        ("import sys\nsys.stderr.write('boom')\nsys.exit(3)\n", "exited 3: boom"),
        ("pass\n", "produced no output"),
    ],
)
def test_failing_generator_leaves_the_checkout_clean(tmp_path, source, expected):
    repo = _repo_with_generator(tmp_path, source)
    worktree, branch_sha, main_sha = _diverge_by_hand(repo)

    status, guard = _gate(repo, worktree)

    assert status == "merge_failed"
    assert expected in guard.outcomes[TASK].reason
    _assert_failed_cleanly(repo, guard, main_sha, branch_sha)
    assert (repo / REPORT).read_text(encoding="utf-8") == "report from main\n"


def test_unexpected_resolver_error_still_aborts_the_merge(tmp_path, monkeypatch):
    """The resolver runs while the main checkout is mid-merge: an exception
    nobody anticipated must end merge_failed with the merge aborted, not
    unwind the gate and leave MERGE_HEAD behind."""
    repo = _repo_with_generator(tmp_path, "print('fresh report')\n")
    worktree, branch_sha, main_sha = _diverge_by_hand(repo)

    def explode() -> dict[str, str]:
        raise RuntimeError("agent env unavailable")

    monkeypatch.setattr("equipa.generated_files.build_agent_env", explode)

    status, guard = _gate(repo, worktree)

    assert status == "merge_failed"
    assert "RuntimeError: agent env unavailable" in guard.outcomes[TASK].reason
    _assert_failed_cleanly(repo, guard, main_sha, branch_sha)
    assert (repo / REPORT).read_text(encoding="utf-8") == "report from main\n"


# --- generator environment ----------------------------------------------------


def test_generator_runs_scrubbed_isolated_and_outside_the_checkout(
    tmp_path, monkeypatch,
):
    repo = _repo_with_generator(tmp_path, (
        "import json, os, sys\n"
        "print(json.dumps({'cwd': os.getcwd(), 'env': sorted(os.environ),\n"
        "                  'isolated': sys.flags.isolated, 'argv': sys.argv[1:],\n"
        "                  'path': sys.path}))\n"
    ))
    worktree, _branch_sha, _main_sha = _diverge_by_hand(repo)
    for name, value in (
        ("DATABASE_URL", "postgres://user:pw@db/equipa"),
        ("ANTHROPIC_API_KEY", "sk-test-not-real"),
        ("CLAUDE_CODE_OAUTH_TOKEN", "oauth-test-not-real"),
        ("GITHUB_TOKEN", "ghp-test-not-real"),
        ("PYTHONPATH", str(repo)),
    ):
        monkeypatch.setenv(name, value)

    status, guard = _gate(repo, worktree)

    assert status == "merged", guard.outcomes[TASK]
    seen = json.loads((repo / REPORT).read_text(encoding="utf-8"))
    for name in ("DATABASE_URL", "ANTHROPIC_API_KEY", "CLAUDE_CODE_OAUTH_TOKEN",
                 "GITHUB_TOKEN", "PYTHONPATH", "THEFORGE_DB"):
        assert name not in seen["env"]
    assert seen["isolated"] == 1
    cwd = Path(seen["cwd"]).resolve()
    assert repo.resolve() not in (cwd, *cwd.parents)
    assert seen["argv"] == ["--repo-root", seen["cwd"], "--stdout"]
    assert str(repo) not in seen["path"] and seen["cwd"] not in seen["path"]
    # Neither the export nor the generator's own directory (scripts/) is
    # importable, so a merged-tree ``scripts/ast.py`` cannot shadow stdlib.
    for entry in seen["path"]:
        # Relative (and empty) entries are relative to the generator's cwd.
        resolved = (cwd / entry).resolve()
        assert cwd not in (resolved, *resolved.parents), entry
    assert not cwd.exists(), "the private export is removed afterwards"


# --- a project without the generator is unaffected ----------------------------


def test_project_without_the_generator_is_unaffected(tmp_path, capsys):
    repo = _init_repo(tmp_path / "repo")
    _write(repo, REPORT, "report v0\n")
    _commit_all(repo, "base")
    worktree, branch_sha, main_sha = _diverge_by_hand(repo)

    status, guard = _gate(repo, worktree)

    assert status == "merge_failed"
    assert guard.outcomes[TASK].reason.startswith("merge and rebase conflict:")
    _assert_failed_cleanly(repo, guard, main_sha, branch_sha)
    assert "generated-files" not in capsys.readouterr().err


# --- merge integrity (task #3116) with a regenerated file ----------------------


def _resolution_commit(repo: Path, main_sha: str, branch_sha: str, **files: str) -> str:
    """A merge commit (main, branch) over the conflicted merge-tree result
    with ``files`` (relative path -> content) replaced."""
    _rc, tree, _ = _merge_tree(repo, main_sha, branch_sha)
    index = repo.parent / "resolution.index"
    env = {**os.environ, "GIT_INDEX_FILE": str(index)}
    subprocess.run(["git", "read-tree", tree], cwd=str(repo), env=env, check=True)
    for rel, content in files.items():
        blob = subprocess.run(
            ["git", "hash-object", "-w", "--stdin"], cwd=str(repo), input=content,
            text=True, capture_output=True, check=True,
        ).stdout.strip()
        subprocess.run(
            ["git", "update-index", "--cacheinfo", f"100644,{blob},{rel}"],
            cwd=str(repo), env=env, check=True,
        )
    new_tree = subprocess.run(
        ["git", "write-tree"], cwd=str(repo), env=env, text=True,
        capture_output=True, check=True,
    ).stdout.strip()
    index.unlink()
    return _git(repo, "commit-tree", new_tree, "-p", main_sha, "-p", branch_sha,
                "-m", "resolution")


@pytest.mark.parametrize(
    ("extra", "accepted"),
    [
        ({}, True),
        ({"equipa/core.py": "import os\nos.system('id')\n"}, False),
    ],
    ids=["report-only", "report-and-code"],
)
def test_guard_accepts_only_a_resolution_that_touches_the_report(
    repo, extra, accepted,
):
    worktree, branch_sha, main_sha = _diverge_with_report_conflict(repo)
    del worktree
    guard = asyncio.run(DefaultBranchGuard.snapshot(repo))
    resolution = _resolution_commit(
        repo, main_sha, branch_sha, **{REPORT: "regenerated\n"}, **extra,
    )
    _git(repo, "update-ref", "refs/heads/main", resolution)

    # Task #3141 (I-03): the guard also requires the verified report blob.
    report_blob = subprocess.run(
        ["git", "hash-object", "--stdin"], cwd=str(repo), input="regenerated\n",
        text=True, capture_output=True, check=True,
    ).stdout.strip()

    recorded = asyncio.run(guard.record_merge(
        TASK, branch_sha, post_head=resolution, regenerated_paths=(REPORT,),
        regenerated_blobs={REPORT: report_blob},
    ))

    assert recorded is accepted
    assert guard.tripped is not accepted


def test_guard_refuses_a_conflicted_merge_without_regenerated_paths(repo):
    """Unchanged #3116 behaviour: a conflicted recomputation never matches
    unless the orchestrator declares the regenerated files."""
    _worktree, branch_sha, main_sha = _diverge_with_report_conflict(repo)
    guard = asyncio.run(DefaultBranchGuard.snapshot(repo))
    resolution = _resolution_commit(
        repo, main_sha, branch_sha, **{REPORT: "regenerated\n"},
    )
    _git(repo, "update-ref", "refs/heads/main", resolution)

    assert asyncio.run(guard.record_merge(
        TASK, branch_sha, post_head=resolution,
    )) is False
    assert guard.tripped


def test_guard_refuses_regenerated_paths_that_did_not_conflict(repo):
    """Declaring a path that git merged cleanly is not a licence to change it."""
    _worktree, branch_sha, main_sha = _diverge_with_report_conflict(repo)
    guard = asyncio.run(DefaultBranchGuard.snapshot(repo))
    resolution = _resolution_commit(
        repo, main_sha, branch_sha,
        **{REPORT: "regenerated\n", "equipa/core.py": "VALUE = 'x'\n"},
    )
    _git(repo, "update-ref", "refs/heads/main", resolution)

    assert asyncio.run(guard.record_merge(
        TASK, branch_sha, post_head=resolution,
        regenerated_paths=(REPORT, "equipa/core.py"),
    )) is False
    assert guard.tripped
